### ISSUE TITLE
Fix Carjacking Bugs (see comments)

### ISSUE THREAD

**Issue by runeparadox** [Notorious-FiveM/Public#432]
Aiming gun at locals not always triggering car jacking
Successful carjacking by aiming gun only, bugs car and prevents entrance to vehicle
Shooting local during carjacking progress bar bugs out the player in the gun draw animation
NO F8's

**Comment by munti00** [comment]
When it's taking keys after killing local and dragging them out of the vehicle, it gives the keys to the player next to you, or no one if no one else if around.
